name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-cli:
    name: Build CLI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: vscode-workspaces-editor
            asset_name: vscode-workspaces-editor-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: vscode-workspaces-editor.exe
            asset_name: vscode-workspaces-editor-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: vscode-workspaces-editor
            asset_name: vscode-workspaces-editor-macos-amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: vscode-workspaces-editor
            asset_name: vscode-workspaces-editor-linux-arm64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact_name: vscode-workspaces-editor.exe
            asset_name: vscode-workspaces-editor-windows-arm64.exe
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: vscode-workspaces-editor
            asset_name: vscode-workspaces-editor-macos-arm64
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            artifact_name: vscode-workspaces-editor
            asset_name: vscode-workspaces-editor-linux-arm

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            pkg-config \
            build-essential \
            libglib2.0-dev \
            libsoup-3.0-dev

      - name: Setup for ARM Linux cross-compilation
        if: matrix.target == 'aarch64-unknown-linux-gnu' || matrix.target == 'armv7-unknown-linux-gnueabihf'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            gcc-arm-linux-gnueabihf \
            g++-arm-linux-gnueabihf \
            libc6-dev-arm64-cross \
            libc6-dev-armhf-cross

          # Add ARM architectures
          sudo dpkg --add-architecture arm64
          sudo dpkg --add-architecture armhf
          sudo apt-get update

          # Install ARM specific development libraries
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            sudo apt-get install -y \
              libglib2.0-dev:arm64 \
              libgtk-3-dev:arm64 \
              libwebkit2gtk-4.1-dev:arm64 \
              libsoup-3.0-dev:arm64
          elif [[ "${{ matrix.target }}" == "armv7-unknown-linux-gnueabihf" ]]; then
            sudo apt-get install -y \
              libglib2.0-dev:armhf \
              libgtk-3-dev:armhf \
              libwebkit2gtk-4.1-dev:armhf \
              libsoup-3.0-dev:armhf
          fi
          
          # Debug: Check if glib-2.0.pc exists for the target architecture
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            echo "Checking for glib-2.0.pc for aarch64..."
            find /usr -name "glib-2.0.pc" | grep aarch64
          elif [[ "${{ matrix.target }}" == "armv7-unknown-linux-gnueabihf" ]]; then
            echo "Checking for glib-2.0.pc for armhf..."
            find /usr -name "glib-2.0.pc" | grep arm
          fi
          
          # Set up PKG_CONFIG for cross-compilation
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            # Set env vars directly for this platform
            echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
            echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
            echo "PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
            
            # Also create a wrapper script as a backup approach
            echo '#!/bin/bash
            export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
            export PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
            export PKG_CONFIG_ALLOW_CROSS=1
            exec pkg-config "$@"' | sudo tee /usr/local/bin/aarch64-linux-gnu-pkg-config
            sudo chmod +x /usr/local/bin/aarch64-linux-gnu-pkg-config
            echo "PKG_CONFIG=/usr/local/bin/aarch64-linux-gnu-pkg-config" >> $GITHUB_ENV
          elif [[ "${{ matrix.target }}" == "armv7-unknown-linux-gnueabihf" ]]; then
            # Set env vars directly for this platform
            echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
            echo "PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
            echo "PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
            
            # Also create a wrapper script as a backup approach
            echo '#!/bin/bash
            export PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig
            export PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig
            export PKG_CONFIG_ALLOW_CROSS=1
            exec pkg-config "$@"' | sudo tee /usr/local/bin/arm-linux-gnueabihf-pkg-config
            sudo chmod +x /usr/local/bin/arm-linux-gnueabihf-pkg-config
            echo "PKG_CONFIG=/usr/local/bin/arm-linux-gnueabihf-pkg-config" >> $GITHUB_ENV
          fi
          
          # Debug: Test pkg-config for glib-2.0
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            echo "Testing pkg-config for glib-2.0 for aarch64..."
            /usr/local/bin/aarch64-linux-gnu-pkg-config --modversion glib-2.0 || echo "pkg-config test failed"
          elif [[ "${{ matrix.target }}" == "armv7-unknown-linux-gnueabihf" ]]; then
            echo "Testing pkg-config for glib-2.0 for arm..."
            /usr/local/bin/arm-linux-gnueabihf-pkg-config --modversion glib-2.0 || echo "pkg-config test failed"
          fi

      - name: Build CLI
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare artifact
        shell: bash
        run: |
          mkdir -p artifacts
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp "target/${{ matrix.target }}/release/${{ matrix.artifact_name }}" "artifacts/${{ matrix.asset_name }}"
          else
            cp "target/${{ matrix.target }}/release/${{ matrix.artifact_name }}" "artifacts/${{ matrix.asset_name }}"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-${{ matrix.target }}
          path: artifacts/${{ matrix.asset_name }}

  build-gui:
    name: Build GUI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # x86_64 builds
          - os: ubuntu-latest
            target: linux
            arch: x64
          - os: macos-latest
            target: macos
            arch: x64
          - os: windows-latest
            target: windows
            arch: x64
          
          # ARM64 builds
          - os: ubuntu-latest
            target: linux
            arch: arm64
          - os: macos-latest
            target: macos
            arch: arm64
          - os: windows-latest
            target: windows
            arch: arm64
          
          # ARM 32-bit for Linux
          - os: ubuntu-latest
            target: linux
            arch: arm

    steps:
      - uses: actions/checkout@v4

      - name: Set Rust target
        id: set-rust-target
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" && "${{ matrix.arch }}" == "arm64" ]]; then
            echo "RUST_TARGET=aarch64-apple-darwin" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.os }}" == "macos-latest" && "${{ matrix.arch }}" == "x64" ]]; then
            echo "RUST_TARGET=x86_64-apple-darwin" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.os }}" == "windows-latest" && "${{ matrix.arch }}" == "arm64" ]]; then
            echo "RUST_TARGET=aarch64-pc-windows-msvc" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.os }}" == "windows-latest" && "${{ matrix.arch }}" == "x64" ]]; then
            echo "RUST_TARGET=x86_64-pc-windows-msvc" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.arch }}" == "arm64" ]]; then
            echo "RUST_TARGET=aarch64-unknown-linux-gnu" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.arch }}" == "arm" ]]; then
            echo "RUST_TARGET=armv7-unknown-linux-gnueabihf" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.arch }}" == "x64" ]]; then
            echo "RUST_TARGET=x86_64-unknown-linux-gnu" >> $GITHUB_OUTPUT
          else
            # This should not happen, but just in case
            echo "RUST_TARGET=" >> $GITHUB_OUTPUT
          fi

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ steps.set-rust-target.outputs.RUST_TARGET != '' && steps.set-rust-target.outputs.RUST_TARGET || '' }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            pkg-config \
            build-essential \
            libglib2.0-dev \
            libsoup-3.0-dev

      - name: Install ARM cross-compilation tools
        if: matrix.os == 'ubuntu-latest' && (matrix.arch == 'arm64' || matrix.arch == 'arm')
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            gcc-arm-linux-gnueabihf \
            g++-arm-linux-gnueabihf \
            libc6-dev-arm64-cross \
            libc6-dev-armhf-cross
          
          sudo dpkg --add-architecture arm64
          sudo dpkg --add-architecture armhf
          sudo apt-get update
          
          # Install ARM architecture libraries with more specific packages
          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
            sudo apt-get install -y \
              libglib2.0-dev:arm64 \
              libgtk-3-dev:arm64 \
              libwebkit2gtk-4.1-dev:arm64 \
              libsoup-3.0-dev:arm64 \
              libatk1.0-dev:arm64 \
              libpango1.0-dev:arm64 \
              libcairo2-dev:arm64
          elif [[ "${{ matrix.arch }}" == "arm" ]]; then
            sudo apt-get install -y \
              libglib2.0-dev:armhf \
              libgtk-3-dev:armhf \
              libwebkit2gtk-4.1-dev:armhf \
              libsoup-3.0-dev:armhf \
              libatk1.0-dev:armhf \
              libpango1.0-dev:armhf \
              libcairo2-dev:armhf
          fi
          
          # Debug: Check if glib-2.0.pc exists for the target architecture
          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
            echo "Checking for glib-2.0.pc for aarch64..."
            find /usr -name "glib-2.0.pc" | grep aarch64
          elif [[ "${{ matrix.arch }}" == "arm" ]]; then
            echo "Checking for glib-2.0.pc for arm..."
            find /usr -name "glib-2.0.pc" | grep arm
          fi
          
          # Set up PKG_CONFIG for cross-compilation
          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
            # Set env vars directly for this platform
            echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
            echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
            echo "PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
            
            # Create a wrapper script as a backup approach
            echo '#!/bin/bash
            export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
            export PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
            export PKG_CONFIG_ALLOW_CROSS=1
            exec pkg-config "$@"' | sudo tee /usr/local/bin/aarch64-linux-gnu-pkg-config
            sudo chmod +x /usr/local/bin/aarch64-linux-gnu-pkg-config
            echo "PKG_CONFIG=/usr/local/bin/aarch64-linux-gnu-pkg-config" >> $GITHUB_ENV
          elif [[ "${{ matrix.arch }}" == "arm" ]]; then
            # Set env vars directly for this platform
            echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
            echo "PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
            echo "PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
            
            # Create a wrapper script as a backup approach
            echo '#!/bin/bash
            export PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig
            export PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig
            export PKG_CONFIG_ALLOW_CROSS=1
            exec pkg-config "$@"' | sudo tee /usr/local/bin/arm-linux-gnueabihf-pkg-config
            sudo chmod +x /usr/local/bin/arm-linux-gnueabihf-pkg-config
            echo "PKG_CONFIG=/usr/local/bin/arm-linux-gnueabihf-pkg-config" >> $GITHUB_ENV
          fi
          
          # Debug: Test pkg-config for glib-2.0
          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
            echo "Testing pkg-config for glib-2.0 for aarch64..."
            /usr/local/bin/aarch64-linux-gnu-pkg-config --modversion glib-2.0 || echo "pkg-config test failed"
          elif [[ "${{ matrix.arch }}" == "arm" ]]; then
            echo "Testing pkg-config for glib-2.0 for arm..."
            /usr/local/bin/arm-linux-gnueabihf-pkg-config --modversion glib-2.0 || echo "pkg-config test failed"
          fi

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install frontend dependencies
        shell: bash
        run: |
          cd src-ui
          pnpm install

      - name: Build frontend
        shell: bash
        run: |
          cd src-ui
          pnpm build
          cd ..

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri app
        shell: bash
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          CARGO_BUILD_TARGET: ${{ steps.set-rust-target.outputs.RUST_TARGET }}
        run: |
          cd src-tauri
          echo "Building for target: ${{ steps.set-rust-target.outputs.RUST_TARGET }}"
          echo "CARGO_BUILD_TARGET=${CARGO_BUILD_TARGET}"
          
          # Use the target specified in CARGO_BUILD_TARGET
          cargo tauri build --target $CARGO_BUILD_TARGET
          cd ..

      - name: Prepare artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p artifacts
          cp target/${{ steps.set-rust-target.outputs.RUST_TARGET }}/release/bundle/*/vscode-workspaces-editor-gui_*.{deb,AppImage} artifacts/vscode-workspaces-editor-gui-linux-${{ matrix.arch }}.{deb,AppImage} 2>/dev/null || true
          cp target/${{ steps.set-rust-target.outputs.RUST_TARGET }}/release/bundle/*/vscode-workspaces-editor-gui-*.rpm artifacts/vscode-workspaces-editor-gui-linux-${{ matrix.arch }}.rpm 2>/dev/null || true

      - name: Prepare artifacts (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p artifacts
          cp -r "target/${{ steps.set-rust-target.outputs.RUST_TARGET }}/release/bundle/macos/"*.app artifacts/vscode-workspaces-editor-gui-macos-${{ matrix.arch }}.app
          cp -r "target/${{ steps.set-rust-target.outputs.RUST_TARGET }}/release/bundle/dmg/"*.dmg artifacts/vscode-workspaces-editor-gui-macos-${{ matrix.arch }}.dmg
          cd artifacts
          zip -r "vscode-workspaces-editor-gui-macos-${{ matrix.arch }}.zip" *.app
          rm -rf *.app

      - name: Prepare artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir artifacts
          copy "target\${{ steps.set-rust-target.outputs.RUST_TARGET }}\release\bundle\msi\*.msi" artifacts\vscode-workspaces-editor-gui-windows-${{ matrix.arch }}.msi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gui-${{ matrix.target }}-${{ matrix.arch }}
          path: artifacts/*

  create-release:
    name: Create Release
    needs: [build-cli, build-gui]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 